Web/LibraryManagement/Models/Reponse/LibraryCard/LibraryCardDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagement.Models.Reponse.LibraryCard
{
    public class LibraryCardDetail
    {
        public int ID { get; set; }
        public string CodeStudent { get; set; }
        public int IDStudent { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Class { get; set; }
        public bool Gender { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int NumberOfViolate { get; set; }
        public int Status { get; set; }
        public string StatusStr => Status == 0 ? "Đang Mở" : (Status == 1 ? "Đang Khóa" : "Khóa Vĩnh Viễn");
        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }
        [DataType(DataType.Date)]
        public DateTime ExpirationDate { get; set; }
    }
}

Web/LibraryManagement/Models/Reponse/LibraryCard/LibraryCardView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagement.Models.Reponse.LibraryCard
{
    public class LibraryCardView
    {
        [Display(Name ="ID Thẻ Thư Viện")]
        public int ID { get; set; }
        [Display(Name ="Mã Sinh Viên")]
        public string CodeStudent { get; set; }
        public int IDStudent { get; set; }
        [Display(Name = "Họ")]
        public string Firstname { get; set; }
        [Display(Name = "Tên")]
        public string LastName { get; set; }
        public string Email { get; set; }
        [Display(Name = "Số Lần Vi Phạm")]
        public int NumberOfViolate { get; set; }
        [Display(Name = "Tình Trạng")]
        public int Status { get; set; }
        public string StatusStr => Status == 0 ? "Đang Mở" : (Status == 1 ? "Đang Khóa" : "Khóa Vĩnh Viễn");
        [Display(Name = "Ngày Tạo")]
        public DateTime CreatedDate { get; set; }
        [Display(Name = "Ngày Hết Hạn")]
        public DateTime ExpirationDate { get; set; }
    }
}

Web/LibraryManagement/Models/Request/BookBorrow/SelectBooks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagement.Models.Request.BookBorrow
{
    public class SelectBooks
    {
        public int IDLC { get; set; }
        public string keyword { get; set; }
    }
}

Web/LibraryManagement/Models/Request/LibraryCard/CancleBookBorrow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagement.Models.Request.LibraryCard
{
    public class CancleBookBorrow
    {
        public int IDBook { get; set; }
        public int IDReceipt { get; set; }
    }
}

Web/LibraryManagement/Models/Request/LibraryCard/CreateBookBorrow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagement.Models.Request.LibraryCard
{
    public class CreateBookBorrow
    {
        public int IDReciept { get; set; }
        public int IDBook { get; set; }
    }
}

Web/LibraryManagement/Controllers/LibraryCardController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;
using LibraryManagement.Models.Reponse.Book;
using LibraryManagement.Models.Reponse.LibraryCard;
using LibraryManagement.Models.Reponse.Receipt;
using LibraryManagement.Models.Request.Book;
using LibraryManagement.Models.Request.BookBorrow;
using LibraryManagement.Models.Request.LibraryCard;
using LibraryManagement.Models.Request.Receipt;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace LibraryManagement.Controllers
{
    public class LibraryCardController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private string _dir;

        public LibraryCardController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _dir = _hostingEnvironment.ContentRootPath;
        }

        private static int IDLibraryCardCreate = 0;
        private static int IDLibraryCardReturn = 0;
        private static int IDReciept = 0;

        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Gets()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                // Skiping number of Rows count  
                var start = Request.Form["start"].FirstOrDefault();
                // Paging Length 10,20  
                var length = Request.Form["length"].FirstOrDefault();
                // Sort Column Name  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                // Sort Column Direction ( asc ,desc)  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                // Search Value from (Search box)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                //Paging Size (10,20,50,100)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                var librarycards = new List<LibraryCardView>();
                var httpWebRequest = (HttpWebRequest)WebRequest.Create("https://localhost:44394/api/librarycard/gets");
                httpWebRequest.ContentType = "application/json";
                httpWebRequest.Method = "GET";

                var response = httpWebRequest.GetResponse();
                {
                    string responseData;
                    Stream responseStream = response.GetResponseStream();
                    try
                    {
                        StreamReader streamReader = new StreamReader(responseStream);
                        try
                        {
                            responseData = streamReader.ReadToEnd();
                        }
                        finally
                        {
                            ((IDisposable)streamReader).Dispose();
                        }
                    }
                    finally
                    {
                        ((IDisposable)responseStream).Dispose();
                    }
                    librarycards = JsonConvert.DeserializeObject<List<LibraryCardView>>(responseData);
                }

                //Sorting  
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    var prop = GetProperty(sortColumn);
                    if (sortColumnDirection == "asc")
                    {
                        librarycards = librarycards.OrderBy(prop.GetValue).ToList();
                    }
                    else
                    {
                        librarycards = librarycards.OrderByDescending(prop.GetValue).ToList();
                    }
                }

                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    librarycards = (from l in librarycards
                                    where l.LastName.Contains(searchValue) ||
                                       l.CodeStudent.Contains(searchValue)
                                    select l).ToList();
                }

                //total number of rows count   
                recordsTotal = librarycards.Count();
                //Paging   
                var data = librarycards.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });

            }
            catch (Exception)
            {
                throw;
            }
        }
        private PropertyInfo GetProperty(string name)
        {
            var properties = typeof(LibraryCardView).GetProperties();
            PropertyInfo prop = null;
            foreach (var item in properties)
            {
                if (item.Name.ToLower().Equals(name.ToLower()))
                {
                    prop = item;
                    break;
                }
            }
            return prop;
        }
        public JsonResult LibraryCardDetail(int id)
        {
            var librarycard = new LibraryCardDetail();
            var url = "https://localhost:44394/api/librarycard/get/" + id;
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream)?.Dispose();
                }

                librarycard = JsonConvert.DeserializeObject<LibraryCardDetail>(responseData);
            }
            return Json(new { response = librarycard, code = 1 });
        }
        public IActionResult CreateReceiptDetail(int IDReceipt)
        {
            var receipt = new ReceiptView();
            var url = "https://localhost:44394/api/librarycard/getreceipt/" + IDReceipt;
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream)?.Dispose();
                }

                receipt = JsonConvert.DeserializeObject<ReceiptView>(responseData);
            }
            return View(receipt);
        }
        public IActionResult ViewBookBorrowByIDLC(int id)
        {
            IDLibraryCardReturn = id;
            var books = new List<LibraryCardBookBorrow>();
            var url = "https://localhost:44394/api/librarycard/getbr/" + id;
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream)?.Dispose();
                }

                books = JsonConvert.DeserializeObject<List<LibraryCardBookBorrow>>(responseData);
            }
            return View(books);
        }
        public IActionResult CreateReceipt(int id)
        {
            var model = new CreateReceipt();
            model.BorrowDate = DateTime.Now;
            model.AppointmentDate = DateTime.Now.AddDays(7);
            model.IDLibraryCard = id;
            var createResult = 0;
            var httpWebRequest = (HttpWebRequest)WebRequest.Create("https://localhost:44394/api/librarycard/createreciept");
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                var json = JsonConvert.SerializeObject(model);

                streamWriter.Write(json);
            }

            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
            {
                var result = streamReader.ReadToEnd();

Web/LibraryManagement/Controllers/ReceiptController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;
using LibraryManagement.Models.Reponse.Receipt;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace LibraryManagement.Controllers
{    
    public class ReceiptController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetReceipts()
        {
            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            // Skiping number of Rows count  
            var start = Request.Form["start"].FirstOrDefault();
            // Paging Length 10,20  
            var length = Request.Form["length"].FirstOrDefault();
            // Sort Column Name  
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            // Sort Column Direction ( asc ,desc)  
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            // Search Value from (Search box)  
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;

            var receipts = new List<ReceiptView>();
            var httpWebRequest = (HttpWebRequest)WebRequest.Create("https://localhost:44394/api/librarycard/getreceipts");
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {

                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream).Dispose();
                }
                receipts = JsonConvert.DeserializeObject<List<ReceiptView>>(responseData);


                //Sorting  
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    var prop = GetProperty(sortColumn);
                    if (sortColumnDirection == "asc")
                    {
                        receipts = receipts.OrderBy(prop.GetValue).ToList();
                    }
                    else
                    {
                        receipts = receipts.OrderByDescending(prop.GetValue).ToList();
                    }
                }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    receipts = (from e in receipts
                                where e.CodeReceipt.Contains(searchValue)

                                select e).ToList();
                }

                //total number of rows count   
                recordsTotal = receipts.Count();
                //Paging   
                var data = receipts.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }           
        }
        private PropertyInfo GetProperty(string name)
        {
            var properties = typeof(ReceiptView).GetProperties();
            PropertyInfo prop = null;
            foreach (var item in properties)
            {
                if (item.Name.ToLower().Equals(name.ToLower()))
                {
                    prop = item;
                    break;
                }
            }
            return prop;
        }
    }
}

Web/LibraryManagement/Views/LibraryCard/Index2.cshtml
@*@model IEnumerable<LibraryManagement.Models.Reponse.LibraryCard.LibraryCardView>
@using LibraryManagement.Models.Request.LibraryCard;
@{
    ViewData["Title"] = "Index";
}

<h1>Library Card</h1>

<form method="post" class="form-inline" asp-controller="LibraryCard" asp-action="Index" style="margin-bottom: 20px">
    <div class="border badge-pill bs-popover-auto border-primary">
        <div>
            <input type="text" name="keyword" class=" badge-pill border-0" />
            <button class="text-info btn btn-outline-light border-0">
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodeStudent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDStudent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfViolate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpirationDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodeStudent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDStudent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfViolate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusStr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpirationDate)
            </td>
            <td>
                @Html.ActionLink("Xem Chi Tiết ", "LibraryCardDetail","LibraryCard", new { id = item.ID }) |               
                @Html.ActionLink("Tạo Phiếu Mượn", "CreateReceipt","LibraryCard", new { IDLC = item.ID })|
                @Html.ActionLink("Xem Phiếu Mượn", "ViewReceipt","LibraryCard", new { IDLC = item.ID })
            </td>
        </tr>
}
    </tbody>
</table>*@

Web/LibraryManagement/Views/LibraryCard/SelectBook.cshtml
@model IEnumerable<LibraryManagement.Models.Reponse.Book.BookView>

@{
    ViewData["Title"] = "SelectBook";
}

<h1>Select Book</h1>

<form method="post" class="form-inline" asp-controller="LibraryCard" asp-action="SelectBook" style="margin-bottom: 20px">
    <div class="border badge-pill bs-popover-auto border-primary">
        <div>
            <input type="text" name="keyword" class=" badge-pill border-0" />
            <button class="text-info btn btn-outline-light border-0">
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
</form>

<a asp-action="ViewBorrowBookByIDReceipt" asp-controller="LibraryCard" asp-route-id="@ViewBag.IDReceipt">Kiểm Tra</a>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>           
            @*<th>
                @Html.DisplayNameFor(model => model.Avatar)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>           
            @*<td>
                @Html.DisplayFor(modelItem => item.Avatar)
            </td>*@
            <td>
                @Html.ActionLink("Chọn", "CreateBookBorrow","LibraryCard", new {  id = item.ID }) 
            </td>
        </tr>
}
    </tbody>
</table>

Web/LibraryManagement/Views/LibraryCard/ViewBookBorrowByIDLC.cshtml
@model IEnumerable<LibraryManagement.Models.Request.LibraryCard.LibraryCardBookBorrow>

@{
    ViewData["Title"] = "ViewBookBorrowByIDLC";
}

<h1>View Book Borrow By IDLC</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IDBook)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberBorrow)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDReceipt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodeReceipt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BorrowDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IDBook)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberBorrow)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDReceipt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodeReceipt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BorrowDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppointmentDate)
            </td>
            <td>
                @Html.ActionLink("Trả Sách", "ReturnBook","LibraryCard", new { IDBook = item.IDBook,IDReceipt = item.IDReceipt }) |
                @Html.ActionLink("Gia Hạn", "Details","LibraryCard", new { /* id=item.PrimaryKey */ }) |               
            </td>
        </tr>
}
    </tbody>
</table>

Web/LibraryManagement/Views/LibraryCard/ViewBorrowBookByIDReceipt.cshtml
@model IEnumerable<LibraryManagement.Models.Request.LibraryCard.ViewBorrowBookByIDReceipt>

@{
    ViewData["Title"] = "ViewBorrowBookByIDReceipt";
}

<h1>View Borrow Book By IDReceipt</h1>

<p>
    <a asp-action="SelectBook" asp-controller="LibraryCard" asp-route-id="@ViewBag.ID">Chọn Sách</a>
</p>
<table class="table">
    <thead>
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.BookCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberBorrow)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodeReceipt)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.IDLibraryCard)
                </th>*@
            <th></th>
        </tr>
    </thead>



    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.BookCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberBorrow)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CodeReceipt)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.IDLibraryCard)
                    </td>*@
                <td>
                    @Html.ActionLink("Hủy", "CancelBookBorrow","LibraryCard", new { IDBook = item.ID }) 
                    
                </td>
            </tr>
        }

    </tbody>
</table>
<p>
    <a asp-action="Index" asp-controller="LibraryCard">Xác Nhận |</a>
    <a asp-action="CancelReceipt" asp-controller="LibraryCard" asp-route-IDReceipt="@ViewBag.IDReceipt">Hủy Bỏ</a>
</p>

Web/LibraryManagement/Views/LibraryCard/ViewBorrowBookFollowReceipt.cshtml
@model IEnumerable<LibraryManagement.Models.Request.LibraryCard.ViewBorrowBookByIDReceipt>

@{
    ViewData["Title"] = "ViewBorrowBookFollowReceipt";
}

<h1>Xem Sách Của Phiếu Mượn</h1>


<table class="table">
    <thead>
        <tr>
            @*<th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IDReceipt)
        </th>*@
            <th>
                @Html.DisplayNameFor(model => model.BookCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            @*<th>
            @Html.DisplayNameFor(model => model.CodeReceipt)
        </th>*@
            @*<th>
            @Html.DisplayNameFor(model => model.IDLibraryCard)
        </th>*@
            <th>
                @Html.DisplayNameFor(model => model.BorrowDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            @*<td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IDReceipt)
        </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.BookCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            @*<td>
            @Html.DisplayFor(modelItem => item.CodeReceipt)
        </td>*@
            @*<td>
            @Html.DisplayFor(modelItem => item.IDLibraryCard)
        </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.BorrowDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppointmentDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusStr)
            </td>
            <td>
                @Html.ActionLink("Trả Sách", "ReturnBook", "LibraryCard", new { IDBook = item.ID, IDReceipt = item.IDReceipt })
            </td>
        </tr>
        }
    </tbody>
</table>
<p>
    @Html.ActionLink("Quay Lại", "ViewReceipt","LibraryCard", new { id = ViewBag.ID }) 
</p>